cs481-ekh/s25-sis

- eis-tracker/app/admin/page.tsx
- eis-tracker/app/login/page.tsx
- eis-tracker/app/middleware.ts
Creates Admin registration page
> Closes Task #62

- eis-tracker/app/api/db/route.test.ts
- eis-tracker/app/api/db/route.ts
- eis-tracker/app/page.tsx
> [#71] implementation of new database functionality

- eis-tracker/app/api/db/route.ts
- eis-tracker/app/page.tsx
> Closes #79

- eis-tracker/app/api/db/route.ts
- eis-tracker/app/page.tsx
> (#88) Fix registration bug

- eis-tracker/app/api/db/route.test.ts
- eis-tracker/app/api/db/route.ts
references #110 
Adds a major field to the users table,
a set_major mode to the POST method,
and a simple test.
> [#110] Major field in users table

- eis-tracker/app/page.tsx
✅ Adds validation to ensure that Student IDs entered on the home page are exactly 9 digits.
Changes:
- Added input validation to `/app/page.tsx`
- Prevents login or registration if ID is invalid
- Displays error message below the Student ID input field
✅ Acceptance Criteria:
- Error message appears if Student ID is invalid
- Valid 9-digit IDs are accepted as before
Closes #109
> [#109] Validate Student ID on Login

- eis-tracker/app/admin/page.tsx
- eis-tracker/app/api/import/route.ts
- eis-tracker/package-lock.json
- eis-tracker/package.json
references #112 
Adds an canvas import form to the admin page and uploads the file.
Returns student options at the moment, does not import to a database.
> [#112] import and upload the canvas export.

- eis-tracker/app/page.tsx
references #111 
When a user logs in without a major selected a popup is created to have the user select a major.
> [#111] Select Major on first login

- eis-tracker/app/api/db/route.test.ts
- eis-tracker/app/api/db/route.ts
Added CardID to the users table and ways to search by the CardID, and set the CardID. See documentation for use.
> [#113] CardID mapping

- eis-tracker/app/admin/page.tsx
- eis-tracker/app/api/db/route.ts
- eis-tracker/app/api/login/route.ts
- eis-tracker/app/login/page.tsx
> #120 Adds admin login DB, minor bug fixes

- eis-tracker/app/api/db/route.ts
New mode in GET all_logged_in, that only returns users who are logged in.
> return only logged in students

- eis-tracker/app/api/db/route.ts
- eis-tracker/app/api/import/route.ts
✅ Moves tag fields (WhiteTag, BlueTag, GreenTag, OrangeTag) directly into the users table and removes the separate training_data table.
Changes:
- Dropped training_data table from database creation
- Added WhiteTag, BlueTag, GreenTag, OrangeTag, and PurpleTag columns to users table
- Updated /api/import/route.ts to insert tag data directly into users
- Updated /api/db/route.ts to calculate Tags bitmask from new fields
- Confirmed Admin page, Login page, CSV import, and log download functionality still work normally
- Full testing walkthrough completed (student login/logout, admin edit, daily CSV import)
✅ Acceptance Criteria:
- No more training_data table exists
- All tag fields stored directly in users table
- CSV upload imports and updates tags correctly
- Student login/logout flow …
> [#170] Move Tag Fields Into Users Table and Remove training_data

- eis-tracker/app/admin/page.tsx
- eis-tracker/app/api/db/route.ts
- eis-tracker/app/page.tsx
disabled costly logs or dangerous modes
> [#157] cleaned console logs and manual mode

- eis-tracker/app/api/import/route.ts
This PR adds detailed logging to the `/api/import` route to help diagnose the 500 Internal Server Error that occurs during file uploads in production. These logs will assist in identifying the exact failure point without exposing anything to the frontend or end users.
**app/api/import/route.ts**  
- Added logs at key points:
- When upload request is received  
- When `FormData` is parsed  
- When buffer is created (and its size)  
- When rows are parsed from CSV  
- When each student is inserted, updated, or skipped  
- Final summary with counts  
- Error block now logs the full exception to console
These logs are internal-only and do not appear in the UI.  
Once this is deployed, the logs should appear in the production server logs, allowing us to debug why uploads fail despite local …
> [#180] Add Detailed Logging to CSV Import Route for Server Error Diagnosis

- eis-tracker/app/admin/page.tsx
- eis-tracker/app/api/import/route.ts
This pull request addresses several key improvements to the `/api/import` backend and the admin upload UI:
- Refactored `route.ts` to properly handle in-memory CSV parsing with `formData.get('file')` and `Blob`.
- Replaced  logic relying on `File` or `fs.writeFile`.
- Ensured all `StudentID` values are trimmed and normalized to prevent `UNIQUE` constraint violations on re-imports.
- Improved database performance by preloading all existing users into memory before batch insert/update.
- Batched inserts and updates using a transaction to reduce locking.
- Admin page UI now prevents rapid double-submits during CSV upload by disabling the upload button while the request is in progress.
---
> Fix CSV Import Upload Logic and UI Submission Handling

- eis-tracker/app/api/db/route.ts
- eis-tracker/app/page.tsx
changed the text input of the home page to be surrounded in a form so that the enter key works.
Now also includes a listener to select the text entry on keypress.
Fixed a bug in how users are returned to fix major selection.
> Better login function and Fix

- eis-tracker/app/admin/page.tsx
- eis-tracker/app/api/db/route.ts
- eis-tracker/app/api/login/route.ts
- eis-tracker/app/page.tsx
- eis-tracker/package-lock.json
- eis-tracker/package.json
References #190 , may also effect #192
> Fixes for passwords and others

- eis-tracker/app/login/page.tsx
✅ Adds a red popup message for failed admin login attempts and clears the password field for better user feedback.
🔧 Changes:
Displays a red "Invalid credentials" alert when the login attempt fails
Clears the password input field after a failed login
Error message disappears when the user begins typing again
No backend or database changes — this is a front-end-only improvement
✅ Acceptance Criteria:
Login failure visibly alerts the user with a red banner
Password is automatically cleared after each failure
No impact to existing login success flow
Fully passes npm run build and tested locally
Style and component structure match existing layout
Closes #191
> [#191] Add Red Popup and Clear Password on Invalid Login

- eis-tracker/app/api/db/route.test.ts
- eis-tracker/app/api/db/route.ts
- eis-tracker/app/page.tsx
References #195 
Also adds some improved logic for logging in and out, and an interval for updating the logged in students.
Large changes came from formatting code for consistent white-space.
A not found user in Get mode:user now returns 404 instead of 400, and test updated to match.
> Better Log-in and out logic

- eis-tracker/app/page.tsx
References #197 
Allows for unknown id's to register themselves to be new users.
Also includes fixes for keypress listener.
> New User registration
